name: Stori Film
favicon: null
layout_spectrum: 0.3650928
typography_spectrum: 0.30784
title: Stori Film
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 1
  lightness: 0.01274368
  saturation: 0.5
  rhythmicContrast: 0.4353276
purpose: []
