typography_spectrum: 0.30784
color:
  brandColors:
    - '#14426b'
    - '#2d6392'
    - '#d6d6d6'
    - '#000000'
    - '#9ba2a7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25697
analytics:
  google: null
  facebook: null
  twitter: null
name: Stori Film
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Stori Film
purpose: []
