name: Stori Film
favicon: null
layout_spectrum: 0.24899
typography_spectrum: 0.31381557416170835
title: Stori Film
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.05044670286588371
  lightness: 0.6197234753053635
  saturation: 0.5737607730552554
  rhythmicContrast: 0.8059599900152534
purpose: []
